export class EndpointConstants {

  public static readonly LOGIN_ENDPOINT = '/api/login'
  public static readonly LOGOUT_ENDPOINT = '/api/logout'
  public static readonly REGISTRATION_ENDPOINT = '/api/registration'
  public static readonly CONFIRM_ENDPOINT = '/api/confirm'
  public static readonly RESTORE_ENDPOINT = '/api/restore'
  public static readonly RESET_PASSWORD_ENDPOINTS = '/api/resetPassword'
  public static readonly REFRESH_TOKEN_ENDPOINT = '/api/refreshToken'
  public static readonly GET_USER_PROFILE_INFO_ENDPOINT = '/api/getUserProfileInfo'
  public static readonly GET_USER_FRIENDS_INFO_ENDPOINT = '/api/getUserFriendsInfo'
  public static readonly GET_MENU_DATA_ENDPOINT = '/api/getMenuData'
  public static readonly ADD_PHOTO_ENDPOINT = '/api/addPhoto'
  public static readonly DELETE_PHOTO_ENDPOINT = '/api/deletePhoto'
  public static readonly CHANGE_PHOTO_LIKE_ENDPOINT = '/api/changePhotoLike'
  public static readonly CREATE_POST_ENDPOINT = '/api/createPost'
  public static readonly DELETE_POST_ENDPOINT = '/api/deletePost'
  public static readonly CHANGE_POST_LIKE_ENDPOINT = '/api/changePostLike'
  public static readonly CREATE_FRIEND_REQUEST_ENDPOINT = '/api/createFriendRequest'
  public static readonly CANCEL_FRIEND_REQUEST_ENDPOINT = '/api/cancelFriendRequest'
  public static readonly DELETE_FRIEND_ENDPOINT = '/api/deleteFriend'
  public static readonly AGREE_FRIEND_REQUEST_ENDPOINT = '/api/agreeFriendRequest'
  public static readonly REJECT_FRIEND_REQUEST_ENDPOINT = '/api/rejectFriendRequest'
  public static readonly GET_POST_LIST_BLOCK_ENDPOINT = '/api/getPostListBlock'
  public static readonly GET_USER_POST_LIST_ENDPOINT = '/api/getUserPostList'
  public static readonly GET_SETTINGS = '/api/getSettings'
  public static readonly SEARCH_USERS_ENDPOINT = '/api/searchUsers'
  public static readonly CHANGE_ADDITIONAL_SETTINGS_ENDPOINT = '/api/changeAdditionalSettings'
  public static readonly CHANGE_BASIC_SETTINGS_ENDPOINT = '/api/changeBasicSettings'
  public static readonly WS_ENDPOINT = '/api/ws'
  public static readonly GET_CHAT_INFO_DATA_ENDPOINT = '/api/getChatInfoData'
  public static readonly GET_WEB_SOCKET_SESSION_KEY_ENDPOINT = '/api/getWebSocketSessionKey'
  public static readonly GET_CHAT_MESSAGE_LIST_BLOCK_ENDPOINT = '/api/getChatMessageListBlock'

}
