export enum FormFields {

  FIRST_NAME = 'FIRST_NAME',
  LAST_NAME = 'LAST_NAME',
  EMAIL = 'EMAIL',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATE_OF_BIRTH = 'DATE_OF_BIRTH',
  SEX = 'SEX',
  RESTORE_KEY = 'RESTORE_KEY',
  ABOUT_YOURSELF = 'ABOUT_YOURSELF',
  CITY = 'CITY',
  SCHOOL = 'SCHOOL',
  UNIVERSITY = 'UNIVERSITY',
  IMAGE = 'IMAGE'

}
